module SRE.Render where

open import SRE.Core

open import Data.Nat.Show using (show)
open import Data.String   using (String; _++_)
open import Data.List     using (List; map; foldr)

private
  nl : String
  nl = "\n"

  showSeverity : Severity → String
  showSeverity warning = "warning"
  showSeverity ticket  = "ticket"
  showSeverity page    = "page"

-- Genera una singola regola Prometheus in formato YAML.
-- L'espressione usa la finestra corta come finestra di rilevamento
-- e la finestra lunga come finestra di conferma (multi-window burn rate).
renderAlert : BurnRateAlert → String
renderAlert a =
  let nm  = BurnRateAlert.alert-name   a
      met = BurnRateAlert.metric        a
      sw  = show (BurnRateAlert.short-window a)
      lw  = show (BurnRateAlert.long-window  a)
      br  = show (BurnRateAlert.burn-rate    a)
      sev = showSeverity (BurnRateAlert.sev  a)
      s   = BurnRateAlert.slo a
      sn  = SLO.slo-name     s
      eb  = SLO.error-budget s
  in
    "  - alert: " ++ nm                                                ++ nl ++
    "    expr: |"                                                       ++ nl ++
    "      rate(" ++ met ++ "_errors_total[" ++ sw ++ "m])"           ++ nl ++
    "        / rate(" ++ met ++ "_total[" ++ sw ++ "m])"              ++ nl ++
    "      > " ++ br ++ " * " ++ eb                                    ++ nl ++
    "      and"                                                         ++ nl ++
    "      rate(" ++ met ++ "_errors_total[" ++ lw ++ "m])"           ++ nl ++
    "        / rate(" ++ met ++ "_total[" ++ lw ++ "m])"              ++ nl ++
    "      > " ++ br ++ " * " ++ eb                                    ++ nl ++
    "    for: 1m"                                                       ++ nl ++
    "    labels:"                                                       ++ nl ++
    "      severity: " ++ sev                                           ++ nl ++
    "      slo: " ++ sn                                                 ++ nl ++
    "    annotations:"                                                  ++ nl ++
    "      summary: \"Burn rate " ++ br ++ "x — " ++ sw ++ "m/" ++ lw ++ "m windows\"" ++ nl

renderAlerts : List BurnRateAlert → String
renderAlerts alerts =
  "# Generated by agdovana — proofs verified by Agda typechecker" ++ nl ++
  "groups:"                                                         ++ nl ++
  "  - name: agdovana"                                              ++ nl ++
  "    rules:"                                                      ++ nl ++
  foldr _++_ "" (map renderAlert alerts)
